create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  hostel text not null,
  block text,
  room text not null,
  floor text not null,
  room_type text not null,
  wants jsonb not null default '{"hostels":[],"blocks":[],"rooms":[],"floors":[]}'::jsonb,
  whatsapp text not null,
  swap_code text not null unique,
  status text not null default 'active' check (status in ('active', 'swapped')),
  created_at timestamptz not null default now()
);

create index if not exists listings_status_created_at_idx
  on public.listings (status, created_at desc);

alter table public.listings enable row level security;

drop policy if exists "Server API manages listings" on public.listings;

create policy "Server API manages listings"
  on public.listings
  for all
  using (false)
  with check (false);
